API 인증키 신청하기

https://opendart.fss.or.kr/mng/userApiKeyListView.do

In [1]:
pip install opendartreader

Collecting opendartreader
  Downloading OpenDartReader-0.2.3-py3-none-any.whl (27 kB)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.10/dist-packages (from opendartreader) (1.5.3)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from opendartreader) (2.31.0)
Collecting requests-file (from opendartreader)
  Downloading requests_file-2.0.0-py2.py3-none-any.whl (4.2 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from opendartreader) (4.9.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from opendartreader) (4.12.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->opendartreader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->opendartreader) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->opendartreader) (1.25.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->opendartreader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->opendartreader) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->opendartreader) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->opendartreader) (2024.2.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->opendartreader) (2.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=0.19.2->opendartreader) (1.16.0)
Installing collected packages: requests-file, opendartreader
Successfully installed opendartreader-0.2.3 requests-file-2.0.0

In [3]:
import OpenDartReader

In [5]:
my_api = "3f28117e1240d256672fa7760499647d8078f40b" #개인정보
dart = OpenDartReader(my_api)

dart.list()  #기업을 지정해서 등록된 공시 확인하기

In [8]:
result = dart.list("삼성전자", start="2023-01-01", end="2023-12-31") #"삼성전자" 대신 기업(종목)코드인 005930를 넣어도 같은 결과가 나온다.
display(result.head())
display(result.shape)

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,최대주주등소유주식변동신고서,20231211800418,삼성전자,20231211,유
1,00126380,삼성전자,005930,Y,[기재정정]임원ㆍ주요주주특정증권등소유상황보고서,20231211000100,최민기,20231211,
2,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20231208000649,김수연,20231208,
3,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20231206000226,최종근,20231206,
4,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20231206000097,문태호,20231206,

(147, 9)

document() #보고서 불러오기 #6번째 컬럼인 rcept_no의 보고서 번호를 인자로 받는다.

In [10]:
doc = dart.document("20231211800418")
print(doc)

<html>
 <head>
  <meta content="gdi" http-equiv="X-UA-TextLayoutMetrics">
  <meta content="text/html; charset=euc-kr" http-equiv="Content-Type">
  <STYLE>
.xforms * { font-family: 돋움체;}
.xforms_title * { font-size: 13pt; padding : 0 0 10 0;}

.xforms table {
    font-size: 10px;
    padding:0px;
    border-collapse:collapse;
    color: #3D3D3D;
}
.xforms td {
    padding-left:0px;
    padding-top:0px;
    border-collapse:collapse;
    line-height:22px;
    color: #3D3D3D;
    /*text-align:right;*/
    vertical-align:middle;
    border: 1px solid #7f7f7f;
}

.xforms span {
    /*display: inline-block;*/
    padding-left:3px;
    padding-right: 1px;
    line-height:22px;
    padding-top:0px;
    padding-bottom:0px;
    text-align:left;
    vertical-align:middle;
    border: 0px solid #DBDBDB;
}

.xforms.img{
    border : 0px;
}

.xforms a:link {

    color: #194866;
    text-decoration: none;
}
.xforms a:active {

    color: #194866;
    text-decoration: none;
}
.xforms a:visited {
    color: #194866;
    text-decoration: none;
}

.xforms A:hover {
    color:008BE3;
    text-decoration: none;
}

.xforms_input{
    border: 0px solid #DBDBDB;
    padding-left:3px;
    padding-right: 1px;
    height:22px;
    padding-top:0px;
    padding-bottom:0px;
    text-align:left;
}
</STYLE>
  <title>삼성전자/최대주주등소유주식변동신고서/(2023.12.11)최대주주등소유주식변동신고서</title>
 </head>
 <body>
  <div class="xforms">
   <div>
    <span class="noprint" style="display:none;width:907px;font-size:10pt;"> </span>
    <div class="xforms_title">
     <div>
      <span style="width:900px;font-weight:bold;text-align:center;">최대주주등소유주식변동신고서</span>
     </div>
    </div>
    <span style="width:907px;font-size:11pt;font-weight:bold;">1. 발행회사 정보</span>
    <table border="1" bordercolordark="white" bordercolorlight="#666666" cellpadding="1" cellspacing="0" id="XFormD1_Form0_Table0" style="margin:0px 0px 20px 0px;width:900px;font-size:10pt;border:1px solid #7f7f7f;">
     <tbody>
      <tr>
       <td rowspan="2" width="57"> <span style="width:57px;font-size:10pt;text-align:center;">회사명</span> </td>
       <td rowspan="2" width="139"> <span class="xforms_input" style="width:139px;font-size:10pt;">삼성전자주식회사</span> </td>
       <td rowspan="2" width="64"> <span style="width:64px;font-size:10pt;text-align:center;">회사코드</span> </td>
       <td rowspan="2" width="90"> <span class="xforms_input" style="width:90px;font-size:10pt;">005930</span> </td>
       <td rowspan="2" width="79"> <span style="width:79px;font-size:10pt;text-align:center;">담당부서명</span> </td>
       <td rowspan="2" width="121"> <span class="xforms_input" style="width:121px;font-size:10pt;">IR팀</span> </td>
       <td rowspan="2" width="65"> <span style="width:65px;font-size:10pt;text-align:center;">담당자명</span> </td>
       <td rowspan="2" width="105"> <span class="xforms_input" style="width:105px;font-size:10pt;">박주현</span> </td>
       <td width="49"> <span style="width:49px;font-size:10pt;text-align:center;">tel</span> </td>
       <td width="131"> <span class="xforms_input" style="width:131px;font-size:10pt;">02-2255-9000</span> </td>
      </tr>
      <tr>
       <td width="49"> <span style="width:49px;font-size:10pt;text-align:center;">(fax)</span> </td>
       <td width="131"> <span class="xforms_input" style="width:131px;font-size:10pt;">02-779-8920</span> </td>
      </tr>
     </tbody>
    </table>
    <span style="width:907px;font-size:11pt;font-weight:bold;">2. 발행주식수 정보</span>
    <table border="1" bordercolordark="white" bordercolorlight="#666666" cellpadding="1" cellspacing="0" id="XFormD1_Form0_Table1" style="margin:0px 0px 20px 0px;width:900px;font-size:10pt;border:1px solid #7f7f7f;">
     <tbody>
      <tr>
       <td width="300"> <span style="width:300px;font-size:10pt;text-align:center;">보통주식총수(1)</span> </td>
       <td width="300"> <span style="width:300px;font-size:10pt;text-align:center;">종류주식총수(2)</span> </td>
       <td width="300"> <span style="width:300px;font-size:10pt;text-align:center;">발행주식총수(1+2)</span> </td>
      </tr>
      <tr>
       <td width="300"> <span class="xforms_input" style="width:300px;font-size:10pt;text-align:right;">5,969,782,550</span> </td>
       <td width="300"> <span class="xforms_input" style="width:300px;font-size:10pt;text-align:right;">822,886,700</span> </td>
       <td width="300"> <span class="xforms_input" style="width:300px;font-size:10pt;text-align:right;">6,792,669,250</span> </td>
      </tr>
     </tbody>
    </table>
    <span style="width:907px;font-size:11pt;font-weight:bold;">3. 보고의 개요</span>
    <table border="1" bordercolordark="white" bordercolorlight="#666666" cellpadding="1" cellspacing="0" id="XFormD1_Form0_Table2" style="margin:0px 0px 20px 0px;width:900px;font-size:10pt;border:1px solid #7f7f7f;">
     <tbody>
      <tr>
       <td colspan="2" rowspan="2" width="360"> <span style="width:360px;font-size:10pt;text-align:center;">보고일자</span> </td>
       <td colspan="3" width="540"> <span style="width:540px;font-size:10pt;text-align:center;">소유주식</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">구분</span> </td>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">주식수</span> </td>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">비율</span> </td>
      </tr>
      <tr>
       <td rowspan="4" width="180"> <span style="width:180px;font-size:10pt;text-align:center;">직전보고서제출일</span> </td>
       <td rowspan="4" width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:center;">2023-11-06</span> </td>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">보통주식</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">1,236,239,387</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">20.71</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">종류주식</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">1,245,414</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0.15</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">증권예탁증권</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0.00</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">합계</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">1,237,484,801</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">18.22</span> </td>
      </tr>
      <tr>
       <td rowspan="4" width="180"> <span style="width:180px;font-size:10pt;text-align:center;">이번보고서제출일</span> </td>
       <td rowspan="4" width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:center;">2023-12-11</span> </td>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">보통주식</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">1,235,909,893</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">20.70</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">종류주식</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">1,165,262</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0.14</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">증권예탁증권</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0.00</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">합계</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">1,237,075,155</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">18.21</span> </td>
      </tr>
      <tr>
       <td colspan="2" rowspan="4" width="360"> <span style="width:360px;font-size:10pt;text-align:center;">증감</span> </td>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">보통주식</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">-329,494</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">-0.01</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">종류주식</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">-80,152</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">-0.01</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">증권예탁증권</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">0.00</span> </td>
      </tr>
      <tr>
       <td width="180"> <span style="width:180px;font-size:10pt;text-align:center;">합계</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">-409,646</span> </td>
       <td width="180"> <span class="xforms_input" style="width:180px;font-size:10pt;text-align:right;">-0.01</span> </td>
      </tr>
     </tbody>
    </table>
    <span class="noprint" style="display:none;width:907px;font-size:10pt;"> </span>
    <span class="noprint" style="display:none;width:907px;font-size:10pt;font-weight:bold;"> </span>
    <span style="width:907px;font-size:11pt;font-weight:bold;">4. 개인별 세부변동사항</span>
    <table border="1" bordercolordark="white" bordercolorlight="#666666" cellpadding="1" cellspacing="0" id="XFormD1_Form0_RepeatTable0" style="margin:0px 0px 20px 0px;width:903px;font-size:10pt;border:1px solid #7f7f7f;">
     <tbody>
      <tr>
       <td colspan="2" width="222"> <span style="width:222px;font-size:10pt;text-align:center;">성명</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">삼성생명(특별계정)</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;">사업자등록번호</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;">104-81-26688</span> </td>
       <td width="134"> <span style="width:134px;font-size:10pt;text-align:center;">성별</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">해당없음</span> </td>
      </tr>
      <tr>
       <td colspan="2" width="222"> <span style="width:222px;font-size:10pt;text-align:center;">국내외 구분</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">국내(법인)</span> </td>
       <td colspan="2" width="276"> <span style="width:276px;font-size:10pt;text-align:center;">국적</span> </td>
       <td colspan="2" width="240"> <span class="xforms_input" style="width:240px;font-size:10pt;">대한민국</span> </td>
      </tr>
      <tr>
       <td colspan="2" width="222"> <span style="width:222px;font-size:10pt;text-align:center;">최대주주 및 발행회사와의 관계</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">기타</span> </td>
       <td width="129"> <span style="width:129px;font-size:10pt;text-align:center;">겸직내용1</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;">-</span> </td>
       <td width="134"> <span style="width:134px;font-size:10pt;text-align:center;">겸직내용2</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">-</span> </td>
      </tr>
      <tr>
       <td width="94"> <span style="width:94px;font-size:10pt;text-align:center;">변경일</span> </td>
       <td width="128"> <span style="width:128px;font-size:10pt;text-align:center;">변경원인</span> </td>
       <td width="165"> <span style="width:165px;font-size:10pt;text-align:center;">주식의 종류</span> </td>
       <td width="129"> <span style="width:129px;font-size:10pt;text-align:center;">변경전주식수</span> </td>
       <td width="147"> <span style="width:147px;font-size:10pt;text-align:center;">증감주식수</span> </td>
       <td width="134"> <span style="width:134px;font-size:10pt;text-align:center;">변경후주식수</span> </td>
       <td width="106"> <span style="width:106px;font-size:10pt;text-align:center;">비고</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-01</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">장내매도(-)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,501,892</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">-4,627</span> </td>
       <td width="134"> <span class="xforms_input" style="width:134px;font-size:10pt;text-align:right;">8,497,265</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">-</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-01</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">장내매수(+)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,497,265</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">5,499</span> </td>
       <td width="134"> <span class="xforms_input" style="width:134px;font-size:10pt;text-align:right;">8,502,764</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">-</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-01</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">기타(-)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,502,764</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">-44,905</span> </td>
       <td width="134"> <span class="xforms_input" style="width:134px;font-size:10pt;text-align:right;">8,457,859</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">ETF 설정</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-02</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">장내매도(-)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,457,859</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">-53</span> </td>
       <td width="134"> <span class="xforms_input" style="width:134px;font-size:10pt;text-align:right;">8,457,806</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">-</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-03</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">장내매도(-)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,457,806</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">-5,611</span> </td>
       <td width="134"> <span class="xforms_input" style="width:134px;font-size:10pt;text-align:right;">8,452,195</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">-</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-03</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">장내매수(+)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,452,195</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">7,935</span> </td>
       <td width="134"> <span class="xforms_input" style="width:134px;font-size:10pt;text-align:right;">8,460,130</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">-</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-06</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">장내매도(-)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,460,130</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">-2,412</span> </td>
       <td width="134"> <span class="xforms_input" style="width:134px;font-size:10pt;text-align:right;">8,457,718</span> </td>
       <td width="106"> <span class="xforms_input" style="width:106px;font-size:10pt;">-</span> </td>
      </tr>
      <tr>
       <td width="94"> <span class="xforms_input" style="width:94px;font-size:10pt;">2023-11-08</span> </td>
       <td width="128"> <span class="xforms_input" style="width:128px;font-size:10pt;">장내매도(-)</span> </td>
       <td width="165"> <span class="xforms_input" style="width:165px;font-size:10pt;">보통주식</span> </td>
       <td width="129"> <span class="xforms_input" style="width:129px;font-size:10pt;text-align:right;">8,457,718</span> </td>
       <td width="147"> <span class="xforms_input" style="width:147px;font-size:10pt;text-align:right;">-12,562</span> </td>

위는 XML 마크업 언어로 되어있다. 필요한 정보만 가져오기 위해서는 몇몇 정보를 파싱해야 한다.

company() #기업의 정보를 불러옴 #인자로 기업의 종목 코드, 고유번호, 회사이름 중 하나를 받는다.

In [16]:
print(dart.company("하나금융지주"))

{'status': '000', 'message': '정상', 'corp_code': '00547583', 'corp_name': '(주)하나금융지주', 'corp_name_eng': 'Hana Financial Group Inc.', 'stock_name': '하나금융지주', 'stock_code': '086790', 'ceo_nm': '함영주', 'corp_cls': 'Y', 'jurir_no': '1101113352004', 'bizr_no': '1078671509', 'adres': '서울특별시 중구 을지로 66 (을지로 2가)', 'hm_url': 'www.hanafn.com', 'ir_url': 'https://www.hanafn.com', 'phn_no': '02-2002-1110', 'fax_no': '02-317-5865', 'induty_code': '64992', 'est_dt': '20051201', 'acc_mt': '12'}

report() #사업보고서의 주요 정보를 가져온다. #회사이름, key_word, 사업연도, 보고서 코드를 인자로 받는다

In [17]:
display(dart.report("하나금융지주", "배당", 2023, "11011")) #11011은 사업보고서 코드

,rcept_no,corp_cls,corp_code,corp_name,se,thstrm,frmtrm,lwfr,stock_knd
0,20240314001628,Y,00547583,하나금융지주,주당액면가액(원),"5,000","5,000","5,000",NaN
1,20240314001628,Y,00547583,하나금융지주,(연결)당기순이익(백만원),"3,421,712","3,552,391","3,526,068",NaN
2,20240314001628,Y,00547583,하나금융지주,(별도)당기순이익(백만원),"1,690,855","1,146,546","1,131,398",NaN
3,20240314001628,Y,00547583,하나금융지주,(연결)주당순이익(원),"11,380","11,803","11,819",NaN
4,20240314001628,Y,00547583,하나금융지주,현금배당금총액(백만원),"979,855","976,738","903,846",NaN
5,20240314001628,Y,00547583,하나금융지주,주식배당금총액(백만원),-,-,-,NaN
6,20240314001628,Y,00547583,하나금융지주,(연결)현금배당성향(%),29.00,27.00,26.00,NaN
7,20240314001628,Y,00547583,하나금융지주,현금배당수익률(%),6.00,7.40,7.00,보통주
8,20240314001628,Y,00547583,하나금융지주,현금배당수익률(%),-,-,-,우선주
9,20240314001628,Y,00547583,하나금융지주,주식배당수익률(%),-,-,-,보통주
10,20240314001628,Y,00547583,하나금융지주,주식배당수익률(%),-,-,-,우선주
11,20240314001628,Y,00547583,하나금융지주,주당 현금배당금(원),"3,400","3,350","3,100",보통주
12,20240314001628,Y,00547583,하나금융지주,주당 현금배당금(원),-,-,-,우선주
13,20240314001628,Y,00547583,하나금융지주,주당 주식배당(주),-,-,-,보통주
14,20240314001628,Y,00547583,하나금융지주,주당 주식배당(주),-,-,-,우선주

finstate() #기업의 재무 제표를 가져온다. #report와 똑같은 인자를 가진다.

In [18]:
display(dart.finstate("하나금융지주", 2023, "11011"))

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,...,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_dt,bfefrmtrm_amount,ord,currency
0,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,자산총계,...,2023.12.31 현재,"591,925,995,000,000",제 18 기,2022.12.31 현재,"568,603,280,000,000",제 17 기,2021.12.31 현재,"502,445,270,000,000",5,KRW
1,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,부채총계,...,2023.12.31 현재,"551,744,278,000,000",제 18 기,2022.12.31 현재,"530,975,132,000,000",제 17 기,2021.12.31 현재,"466,945,930,000,000",11,KRW
2,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,자본금,...,2023.12.31 현재,"1,501,210,000,000",제 18 기,2022.12.31 현재,"1,501,210,000,000",제 17 기,2021.12.31 현재,"1,501,210,000,000",13,KRW
3,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,이익잉여금,...,2023.12.31 현재,"25,126,145,000,000",제 18 기,2022.12.31 현재,"23,186,528,000,000",제 17 기,2021.12.31 현재,"20,824,212,000,000",17,KRW
4,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,자본총계,...,2023.12.31 현재,"40,181,717,000,000",제 18 기,2022.12.31 현재,"37,628,148,000,000",제 17 기,2021.12.31 현재,"35,499,340,000,000",21,KRW
5,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,법인세차감전 순이익,...,2023.01.01 ~ 2023.12.31,"4,681,212,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"4,943,316,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"4,904,925,000,000",27,KRW
6,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,당기순이익,...,2023.01.01 ~ 2023.12.31,"3,468,356,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"3,639,410,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"3,581,582,000,000",29,KRW
7,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,예수부채,...,2023.12.31 현재,"371,866,240,000,000",제 18 기,2022.12.31 현재,"362,575,964,000,000",제 17 기,2021.12.31 현재,"325,149,095,000,000",31,KRW
8,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,차입부채,...,2023.12.31 현재,"43,590,349,000,000",제 18 기,2022.12.31 현재,"37,087,312,000,000",제 17 기,2021.12.31 현재,"30,261,598,000,000",33,KRW
9,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,당기손익-공정가치측정금융자산,...,2023.12.31 현재,"54,605,832,000,000",제 18 기,2022.12.31 현재,"52,374,699,000,000",제 17 기,2021.12.31 현재,"38,718,285,000,000",35,KRW
10,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,기타포괄손익-공정가치측정금융자산,...,2023.12.31 현재,"44,313,496,000,000",제 18 기,2022.12.31 현재,"37,779,945,000,000",제 17 기,2021.12.31 현재,"39,473,529,000,000",37,KRW
11,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,보험계약자산,...,2023.12.31 현재,"7,718,000,000",제 18 기,2022.12.31 현재,"2,826,000,000",제 17 기,2021.12.31 현재,-,41,KRW
12,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,BS,재무상태표,보험계약부채,...,2023.12.31 현재,"5,546,506,000,000",제 18 기,2022.12.31 현재,"5,389,087,000,000",제 17 기,2021.12.31 현재,-,43,KRW
13,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,순이자손익,...,2023.01.01 ~ 2023.12.31,"8,879,449,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"9,006,015,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"7,437,205,000,000",51,KRW
14,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,이자수익,...,2023.01.01 ~ 2023.12.31,"23,275,944,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"15,984,691,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"10,867,491,000,000",53,KRW
15,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,이자비용,...,2023.01.01 ~ 2023.12.31,"-14,396,495,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"-6,978,676,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"-3,430,286,000,000",55,KRW
16,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,파생상품관련손익,...,2023.01.01 ~ 2023.12.31,"25,306,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"-67,719,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"-51,735,000,000",57,KRW
17,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,영업이익(손실),...,2023.01.01 ~ 2023.12.31,"4,693,407,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"4,688,282,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"4,631,096,000,000",59,KRW
18,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,당기순이익(손실),...,2023.01.01 ~ 2023.12.31,"3,468,356,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"3,639,410,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"3,581,582,000,000",61,KRW
19,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,총포괄손익,...,2023.01.01 ~ 2023.12.31,"4,000,135,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"2,852,700,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"3,644,121,000,000",63,KRW
20,20240314001628,11011,2023,00547583,086790,CFS,연결재무제표,IS,손익계산서,순수수료손익,...,2023.01.01 ~ 2023.12.31,"1,977,733,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"1,715,071,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"1,741,717,000,000",67,KRW
21,20240314001628,11011,2023,00547583,086790,OFS,재무제표,BS,재무상태표,자산총계,...,2023.12.31 현재,"24,941,617,000,000",제 18 기,2022.12.31 현재,"25,043,565,000,000",제 17 기,2021.12.31 현재,"23,768,470,000,000",6,KRW
22,20240314001628,11011,2023,00547583,086790,OFS,재무제표,BS,재무상태표,부채총계,...,2023.12.31 현재,"5,873,242,000,000",제 18 기,2022.12.31 현재,"6,426,856,000,000",제 17 기,2021.12.31 현재,"5,924,345,000,000",12,KRW
23,20240314001628,11011,2023,00547583,086790,OFS,재무제표,BS,재무상태표,자본금,...,2023.12.31 현재,"1,501,210,000,000",제 18 기,2022.12.31 현재,"1,501,210,000,000",제 17 기,2021.12.31 현재,"1,501,210,000,000",15,KRW
24,20240314001628,11011,2023,00547583,086790,OFS,재무제표,BS,재무상태표,이익잉여금,...,2023.12.31 현재,"5,819,186,000,000",제 18 기,2022.12.31 현재,"5,661,295,000,000",제 17 기,2021.12.31 현재,"5,708,935,000,000",19,KRW
25,20240314001628,11011,2023,00547583,086790,OFS,재무제표,BS,재무상태표,자본총계,...,2023.12.31 현재,"19,068,375,000,000",제 18 기,2022.12.31 현재,"18,616,709,000,000",제 17 기,2021.12.31 현재,"17,844,125,000,000",22,KRW
26,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,법인세차감전 순이익,...,2023.01.01 ~ 2023.12.31,"1,696,482,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"1,140,398,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"1,129,846,000,000",28,KRW
27,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,당기순이익,...,2023.01.01 ~ 2023.12.31,"1,690,855,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"1,146,546,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"1,131,398,000,000",30,KRW
28,20240314001628,11011,2023,00547583,086790,OFS,재무제표,BS,재무상태표,당기손익-공정가치측정금융자산,...,2023.12.31 현재,"647,818,000,000",제 18 기,2022.12.31 현재,"868,645,000,000",제 17 기,2021.12.31 현재,"479,000,000,000",36,KRW
29,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,순이자손익,...,2023.01.01 ~ 2023.12.31,"-144,221,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"-119,028,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"-103,477,000,000",52,KRW
30,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,이자수익,...,2023.01.01 ~ 2023.12.31,"5,209,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"6,766,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"7,463,000,000",54,KRW
31,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,이자비용,...,2023.01.01 ~ 2023.12.31,"149,430,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"125,794,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"110,940,000,000",56,KRW
32,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,영업이익(손실),...,2023.01.01 ~ 2023.12.31,"1,714,108,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"1,166,133,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"1,152,931,000,000",60,KRW
33,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,당기순이익(손실),...,2023.01.01 ~ 2023.12.31,"1,690,855,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"1,146,546,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"1,131,398,000,000",62,KRW
34,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,총포괄손익,...,2023.01.01 ~ 2023.12.31,"1,689,676,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"1,148,569,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"1,131,991,000,000",64,KRW
35,20240314001628,11011,2023,00547583,086790,OFS,재무제표,IS,손익계산서,순수수료손익,...,2023.01.01 ~ 2023.12.31,"-11,485,000,000",제 18 기,2022.01.01 ~ 2022.12.31,"-14,795,000,000",제 17 기,2021.01.01 ~ 2021.12.31,"-18,344,000,000",68,KRW

In [21]:
hana = dart.finstate("하나금융지주", 2023, "11011")
hana = hana.loc[hana['fs_nm']=="연결재무제표"] #fs_nm: 연결명 / sj_nm: 재무제표 명
hana = hana.loc[hana["account_nm"].isin(["당기순이익","영업이익","매출액"])] # account_nm: 계정명/ 그 중 당기순이익, 영업이익, 매출액을 추출하는 명령어
hana = hana.loc[:,["account_nm","fs_nm","sj_nm","thstrm_dt","thstrm_amount"]] # 모든 행에서 다음과 같은 컬럼을 추출해라
display(hana)

  account_nm   fs_nm  sj_nm                thstrm_dt      thstrm_amount
6      당기순이익  연결재무제표  손익계산서  2023.01.01 ~ 2023.12.31  3,468,356,000,000